/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2014-2015 mezz
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

package mezz.jei.api.recipe.advanced;

import mezz.jei.api.ingredients.ITypedIngredient;

import java.util.List;

/**
 * A simpler version of {@link IRecipeManagerPlugin} that only handles one type of recipe.
 * Unlike the more complex {@link IRecipeManagerPlugin}, catalysts are handled automatically,
 * and the interface is streamlined to handle only one type.
 *
 * Recipes can be generated by this plugin dynamically in response to players looking up recipes.
 * This is useful when your mod has dynamic recipes with too many inputs or outputs to create normal recipes.
 *
 * @since 19.16.0
 */
public interface ISimpleRecipeManagerPlugin<T> {
	/**
	 * @return true if this ingredient is an input to a recipe generated by this plugin.
	 *
	 * @since 19.16.0
	 */
	boolean isHandledInput(ITypedIngredient<?> input);

	/**
	 * @return true if this ingredient is an output to a recipe generated by this plugin.
	 *
	 * @since 19.16.0
	 */
	boolean isHandledOutput(ITypedIngredient<?> output);

	/**
	 * @return all the recipes that have this ingredient as an input.
	 *
	 * @since 19.16.0
	 */
	List<T> getRecipesForInput(ITypedIngredient<?> input);

	/**
	 * @return all the recipes that have this ingredient as an output.
	 *
	 * @since 19.16.0
	 */
	List<T> getRecipesForOutput(ITypedIngredient<?> output);

	/**
	 * @return some recipes that can be generated by this plugin, to show as an example
	 * when players are browsing all recipes.
	 *
	 * @since 19.16.0
	 */
	List<T> getAllRecipes();
}
