package org.complexityanalyzer.bytecode;

public enum SemanticTag {

    // Мир / блоки
    WORLD_MUTATION,
    BLOCK_CHECK,
    REDSTONE_CHECK,
    TAG_CHECK,
    DATA_COMPONENT_CHECK,

    // Сущности
    ENTITY_SPAWN,
    ENTITY_KILL,
    ENTITY_CHECK,

    // Предметы
    ITEM_CONSUME,
    ITEM_PRODUCE,
    ITEM_GIVE,
    ITEM_MOVE,
    ITEM_HELD_CHECK,
    ITEM_GET_TYPE,
    INVENTORY_ACCESS,

    // Энергия / жидкость
    ENERGY_CONSUME,
    ENERGY_PRODUCE,
    FLUID_CONSUME,
    FLUID_PRODUCE,

    // Рецепты
    RECIPE_INPUT,
    RECIPE_OUTPUT,
    RECIPE_PROCESS,
    RECIPE_FLUID_INPUT,
    RECIPE_FLUID_OUTPUT,
    RECIPE_ENERGY_COST,
    RECIPE_DURATION,
    RECIPE_CIRCUIT,
    RECIPE_BUILDER_START,
    MACHINE_DEFINITION,
    MACHINE_RECIPE_TYPE,
    MACHINE_TIER,
    MACHINE_MULTIBLOCK,
    MACHINE_WORKABLE_LOGIC,
    MACHINE_CAPABILITY,

    // Игрок / состояния
    PLAYER_INTERACT,
    GUI_OPEN,
    PLAYER_HURT,
    PLAYER_HEAL,
    PLAYER_STATE_SPRINT,
    PLAYER_STATE_JUMP,
    PLAYER_STATE_SNEAK,
    PLAYER_STATE_GROUND,
    PLAYER_STATE_FLY,
    PLAYER_STATE_SWIM,
    PLAYER_STATE_BURN,
    PLAYER_STATE_RIDING,

    // Условия окружения
    TIME_CHECK,
    DIMENSION_CHECK,
    BIOME_CHECK,
    WEATHER_CHECK,
    EXPERIENCE_CHECK,
    STATUS_EFFECT_CHECK,
    LOOT_TABLE_CHECK,

    // Capability
    CAPABILITY_CHECK,

    // Мета / звук / сообщения
    PLAY_SOUND,
    SEND_MESSAGE,

    // Тик
    TICK
}
